name: ci 

concurrency: 
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - master 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs_pymdownx_material_extras
      - run: mkdocs gh-deploy --force
